version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

formatters:
  enable:
    - goimports
    - gci

  settings:
    goimports:
      local-prefixes: 
       - github.com/chapar-rest/chapar
    gci:
      sections:
        - standard
        - default
        - "prefix(github.com/chapar-rest/chapar)"
        - localmodule

run:
  modules-download-mode: vendor
  timeout: 5m
