name: Build MacOS

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.1

    - name: Install gogio tool
      run: go install gioui.org/cmd/gogio@latest

    - name: Build macos amd64
      run: make build_macos

    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: Upload MacOS
        path: dist
