name: Build Linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Update dependencies
      run: sudo apt-get update

    - name: Install specific dependencies
      run: sudo apt install gcc pkg-config libwayland-dev libx11-dev libx11-xcb-dev libxkbcommon-x11-dev libgles2-mesa-dev libegl1-mesa-dev libffi-dev libxcursor-dev libvulkan-dev

    - name: Checkout repo
      uses: actions/checkout@v4
    
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.1

    - name: Build linux amd64
      run: make linux

    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: Upload Linux
        path: dist
