name: ci
on: [pull_request]
permissions:
  contents: 'read'
  pull-requests: 'read'
jobs:
  lint_and_test:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: false

      - name: Cache (dependencies)
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-v2
          restore-keys: |
            ${{ runner.os }}-go-      

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.58.2
          only-new-issues: true
          install-mode: "binary"

      - name: Libraries for gio
        run: |
          sudo apt update
          sudo apt install libwayland-dev libx11-dev libx11-xcb-dev libxkbcommon-x11-dev libgles2-mesa-dev libegl1-mesa-dev libffi-dev libxcursor-dev libvulkan-dev

      - name: Lint Test
        run: go test -v ./... && golangci-lint run --config=golangci.yaml --issues-exit-code=0
